print("Welcome to the Band Name Generator.")
city = input("What the name of the city you grew up in?\n")
print()
pet = input("What's the name of your favorite pet?\n")
print()
print(f"Your band name could be {city} {pet}.")
